export { HeroSection } from './HeroSection'
export { TrustBarSection } from './TrustBarSection'
export { AboutSection } from './AboutSection'
export { FeaturedProjectsSection } from './FeaturedProjectsSection'
export { ProofOfWorkSection } from './ProofOfWorkSection'
export { TimelineSection } from './TimelineSection'
export { ContactSection } from './ContactSection'
